 
 # ansible-playbook config.yml
 #
 # Tasks for copying configuration files
 #
- hosts: localhost
  connection: local
  become: true
  tasks:
  - name: Copy putty config files
    copy:
      src: putty/
      dest: /home/jeff/.putty/
      owner: jeff
      group: jeff
      force: no
  #    mode: '0644'
  
  - name: Copy remmina config files
    copy:
      src: remmina/
      dest: /home/jeff/.remmina/
      owner: jeff
      group: jeff
      force: no
  #    mode: '0644'

  - name: copy commonly used latex packages to local tex directory tree
    copy:
      src: latex/
      dest: /home/jeff/texmf/tex/latex/jaj/
      owner: jeff
      group: jeff
      force: no
      