 # ansible-playbook local.yml
- hosts: localhost
  connection: local
  become: true
  tasks:
  - name: Install packages
    apt: 
      name:
        # Basic GUI stuff
        - xorg # x window server
        - sddm # display manager - provides graphical login
        - kde-plasma-desktop # basic kde desktop
        # sudo systemctl set-default graphical.target
        # AV software
        - clamav
        - clamtk
        # Office apps
        - libreoffice
        - okular
        - skanlite # scanner software
        - pdfarranger # split and merge
        - firefox
        - thunderbird
        - chromium
        - vlc
        - owncloud-client
        - Elisa # music player
        # Virtualization
        - virtualbox
        - vagrant
        # Remote access to UST
        - putty
        - remmina
        # Graphics
        - inkscape
        - gimp
        - imagemagick
        - imagej
        # Multimedia
        - openshot
        - kdenlive
        - blender
        # Engineering Software
        - kicad
        - freecad
        # document preparation
        - texlive
        - texstudio
        - pandoc
        - pandoc-citeproc
        - pandoc-sidenote
