 # ansible-playbook local.yml
- hosts: localhost
  connection: local
  become: true
  tasks:
  - name: Install packages
    apt: 
      name:
        - clamav
        - clamtk
        - firefox
        - thunderbird
        - vlc
        - virtualbox
        - putty
        - remmina
        - openshot
        - kdenlive
        - vagrant
        - kicad
        - freecad
        - owncloud-client
        
