 # ansible-playbook local.yml
- hosts: localhost
  connection: local
  become: true
  tasks:
  - name: Install packages
    apt: 
      name:
        - xorg # x window server
        - sddm # display manager
        - kde-plasma-desktop # basic kde desktop
        - libreoffice
        - clamav
        - clamtk
        - firefox
        - thunderbird
        - vlc
        - virtualbox
        - putty
        - remmina
        - openshot
        - kdenlive
        - vagrant
        - kicad
        - freecad
        - owncloud-client
        - texlive
        - texstudio
        - pandoc
        - pandoc-citeproc
        - pandoc-sidenote
