- hosts: localhost
  roles:
    - role: gantsign.visual-studio-code
      users:
        - username: jeff
          visual_studio_code_extensions:
            - shd101wyy.markdown-preview-enhanced
            - notZaki.pandocciter
            - DougFinke.vscode-pandoc
          visual_studio_code_settings_overwrite: yes
          visual_studio_code_settings: {
            "editor.rulers": [80, 100, 120],
            "editor.renderWhitespace": true,
            "files.associations": {
              "Vagrantfile": "ruby"
            }
          }
